import type { LevelDefinition, ParcelDefinition } from './engine';

export const ADDRESSES = {
  A: { id: 'A', name: "Ada's bakery", color: '#f4b34c', shape: 'circle' },
  B: { id: 'B', name: "Bea's bookshop", color: '#8bbac3', shape: 'square' },
  C: { id: 'C', name: 'Clover flowers', color: '#cfacd2', shape: 'triangle' },
  D: { id: 'D', name: "Dot's diner", color: '#ed9b81', shape: 'diamond' },
} as const satisfies Record<string, ParcelDefinition>;

export const LEVELS: readonly LevelDefinition[] = [
  {
    id: 'maple-mews',
    title: 'Maple Mews',
    district: 'The practice round',
    briefing: "One parcel, one friendly address. Pick up A and bring it to Ada's bakery before your move allowance runs out.",
    tip: 'No need to park or press a pickup button. Just drive onto a parcel, then onto its matching lettered building.',
    capacity: 1,
    moveBudget: 12,
    scenery: 'garden',
    map: [
      '@.a..',
      '.##..',
      '...#.',
      '.#...',
      '...A.',
    ],
    parcels: [ADDRESSES.A],
  },
  {
    id: 'market-loop',
    title: 'Market Loop',
    district: 'Room for one more',
    briefing: 'The market is open and the van has two slots. Collect a pair of parcels before turning toward their matching shops.',
    tip: 'A two-slot bag lets you combine errands. Plan the order of your pickups and deliveries before setting off.',
    capacity: 2,
    moveBudget: 14,
    scenery: 'town',
    map: [
      '@.a.b.',
      '.##.#.',
      '.A..B.',
      '.#.#..',
      '......',
    ],
    parcels: [ADDRESSES.A, ADDRESSES.B],
  },
  {
    id: 'bottle-neck',
    title: 'Bottle Neck',
    district: 'The little-van challenge',
    briefing: 'Three deliveries, but only one bag slot. You may pass over a parcel with a full bag; it stays on the street until you return.',
    tip: 'You will cross B while carrying A. Deliver A first, then come back with an empty slot. Passing a waiting parcel still costs a move.',
    capacity: 1,
    moveBudget: 22,
    scenery: 'town',
    map: [
      '@.ab.B.',
      '.##.##.',
      '...A.c.',
      '.#.#.#.',
      '.C.....',
    ],
    parcels: [ADDRESSES.A, ADDRESSES.B, ADDRESSES.C],
  },
  {
    id: 'canal-crossing',
    title: 'Canal Crossing',
    district: 'Mind the one-way bridges',
    briefing: 'Two banks, two bridges, three deliveries. The upper bridge goes right; the lower bridge goes left. A return trip needs a little forethought.',
    tip: 'An arrow controls how you LEAVE its tile. You can enter from any adjacent street, but must leave in the arrow’s direction.',
    capacity: 2,
    moveBudget: 32,
    scenery: 'canal',
    map: [
      '@a.#.A.',
      '.#.#.#.',
      '...→b..',
      '.#.#.#.',
      '.B.←...',
      '..c#.C.',
    ],
    parcels: [ADDRESSES.A, ADDRESSES.B, ADDRESSES.C],
  },
  {
    id: 'closing-time',
    title: 'Closing Time',
    district: 'The final collection',
    briefing: 'Four shops are waiting on both sides of town. Two bag slots, one-way crossings, and a snug move allowance: make every turn count.',
    tip: 'A full bag is not a roadblock. Sometimes leaving a parcel for the return trip is the best route. The hint button checks your actual position.',
    capacity: 2,
    moveBudget: 38,
    scenery: 'town',
    map: [
      '@.a#..B',
      '.#.#.#.',
      'b..→..c',
      '.#.#.#.',
      'A..←..D',
      '.#.#.#.',
      '..C#d..',
    ],
    parcels: [ADDRESSES.A, ADDRESSES.B, ADDRESSES.C, ADDRESSES.D],
  },
];
