export interface DictionaryEntry {
  readonly word: string;
  readonly meaning: string;
}

// Deliberately finite, hand-selected vocabulary. These short glosses are original.
const vocabulary: readonly (readonly [string, string])[] = [
  ['BAKE', 'Cook with dry heat.'],
  ['BALL', 'A round object used in games.'],
  ['BAND', 'A group of musicians, or a strip of material.'],
  ['BARD', 'A poet or storyteller.'],
  ['BARE', 'Not covered.'],
  ['BARK', 'A tree’s outer layer, or a dog’s call.'],
  ['BARN', 'A farm building.'],
  ['BASH', 'Hit forcefully; also an informal party.'],
  ['BATH', 'Washing by sitting in water.'],
  ['BEAD', 'A small object with a hole for threading.'],
  ['BEAM', 'A ray of light, or a supporting timber.'],
  ['BEAR', 'A large mammal; also to carry or endure.'],
  ['BEAT', 'A regular pulse, or to defeat.'],
  ['BEEN', 'A form of the verb “be.”'],
  ['BEER', 'A fermented grain drink.'],
  ['BELL', 'A hollow object that rings when struck.'],
  ['BEND', 'Make something curve.'],
  ['BENT', 'Curved rather than straight.'],
  ['BEST', 'Better than all the others.'],
  ['BILL', 'An amount owed, or a bird’s beak.'],
  ['BIRD', 'An animal with feathers.'],
  ['BOAR', 'A male pig.'],
  ['BOAT', 'A small vessel for travelling on water.'],
  ['BOLD', 'Confident and willing to take risks.'],
  ['BOND', 'A connection, or a promise of repayment.'],
  ['BONE', 'A hard part of a skeleton.'],
  ['BOOK', 'Bound pages, or to make a reservation.'],
  ['BOON', 'Something helpful or welcome.'],
  ['BOOT', 'Footwear that covers the ankle or more.'],
  ['BORE', 'Make a hole, or make someone lose interest.'],
  ['BURN', 'Be consumed or damaged by fire.'],
  ['CARD', 'A small rectangle of stiff paper.'],
  ['CARE', 'Attention given to someone or something.'],
  ['CART', 'A small wheeled vehicle.'],
  ['CASE', 'A container, example, or legal matter.'],
  ['CASH', 'Money in coins or notes.'],
  ['CAST', 'Throw, shape in a mould, or a group of actors.'],
  ['CAVE', 'A natural underground space.'],
  ['CLAD', 'Dressed or covered.'],
  ['CLAM', 'A shellfish with two hinged shells.'],
  ['CLAN', 'A group linked by family or shared identity.'],
  ['CLAP', 'Strike the palms together.'],
  ['CLAY', 'Fine earth that can be shaped when wet.'],
  ['CLIP', 'A small fastener; also to trim.'],
  ['COAL', 'A dark rock burned as fuel.'],
  ['COAT', 'An outer garment or a covering layer.'],
  ['CODE', 'A system of symbols or instructions.'],
  ['COLD', 'At a low temperature.'],
  ['COME', 'Move towards a place or person.'],
  ['CONE', 'A shape tapering from a circle to a point.'],
  ['COOK', 'Prepare food with heat.'],
  ['COOL', 'Moderately cold.'],
  ['COPE', 'Manage a difficult situation.'],
  ['CORD', 'A length of thin rope.'],
  ['CORE', 'The central part.'],
  ['CORK', 'Lightweight tree bark used for stoppers.'],
  ['CORN', 'A cereal crop with edible grains.'],
  ['COVE', 'A small sheltered inlet.'],
  ['CURE', 'Restore health, or preserve food.'],
  ['DAME', 'A title of honour for a woman.'],
  ['DARE', 'Have the courage to do something.'],
  ['DARN', 'Mend a hole with stitches.'],
  ['DASH', 'Move quickly; also a punctuation mark.'],
  ['DATE', 'A calendar day, or a sweet fruit.'],
  ['DAWN', 'The first light of day.'],
  ['DEAL', 'An agreement, or to distribute cards.'],
  ['DEAR', 'Loved or valued.'],
  ['DEED', 'An action, or a legal document.'],
  ['DEEP', 'Extending far below a surface.'],
  ['DEER', 'A hoofed animal, often with antlers.'],
  ['DINE', 'Eat a meal.'],
  ['DISH', 'A plate or a prepared food.'],
  ['DIVE', 'Plunge into water or move sharply down.'],
  ['DOOR', 'A movable entrance panel.'],
  ['DOVE', 'A bird related to a pigeon.'],
  ['DOWN', 'Towards a lower place, or soft feathers.'],
  ['DUSK', 'The fading light before night.'],
  ['DUST', 'Fine dry particles.'],
  ['EAST', 'The direction of sunrise.'],
  ['EASY', 'Not difficult.'],
  ['FACE', 'The front of the head, or to confront.'],
  ['FACT', 'Something that is true.'],
  ['FADE', 'Gradually lose colour or strength.'],
  ['FAIL', 'Not achieve the intended result.'],
  ['FALL', 'Move downwards; also the autumn season.'],
  ['FAME', 'The state of being widely known.'],
  ['FARE', 'A travel price, or food on offer.'],
  ['FARM', 'Land used to grow crops or raise animals.'],
  ['FAST', 'Moving quickly, or not eating for a time.'],
  ['FATE', 'An outcome thought to be beyond control.'],
  ['FEAR', 'A feeling caused by danger.'],
  ['FEAT', 'An impressive achievement.'],
  ['FEED', 'Give food to someone or something.'],
  ['FEEL', 'Sense through touch or emotion.'],
  ['FEET', 'More than one foot.'],
  ['FELL', 'Cut down a tree; also the past of “fall.”'],
  ['FELT', 'A pressed-fibre fabric; also the past of “feel.”'],
  ['FILE', 'A stored document, or a smoothing tool.'],
  ['FILL', 'Make full.'],
  ['FILM', 'A moving-picture work or a thin layer.'],
  ['FIND', 'Discover or locate.'],
  ['FINE', 'Very good, thin, or a financial penalty.'],
  ['FIRE', 'Burning that produces heat and light.'],
  ['FIRM', 'Solid or steady; also a business.'],
  ['FISH', 'An animal that lives in water and has gills.'],
  ['FIST', 'A tightly closed hand.'],
  ['FIVE', 'The number after four.'],
  ['FOAM', 'A mass of small bubbles.'],
  ['FOLD', 'Bend one part over another.'],
  ['FOOD', 'Something eaten for nourishment.'],
  ['FOOL', 'Trick someone, or a person acting unwisely.'],
  ['FOOT', 'The end of a leg, or a unit of length.'],
  ['FORD', 'A shallow place where a river can be crossed.'],
  ['FORM', 'A shape, or a document with spaces to fill.'],
  ['FORT', 'A defended building.'],
  ['FULL', 'Containing as much as it can hold.'],
  ['FUSE', 'Join together, or an electrical safety device.'],
  ['GAME', 'An activity with rules and a goal.'],
  ['GATE', 'A movable barrier in an entrance.'],
  ['GAVE', 'The past of “give.”'],
  ['GEAR', 'Equipment, or a toothed wheel.'],
  ['GIVE', 'Pass something to someone else.'],
  ['GOAL', 'An aim or a scoring area.'],
  ['GOAT', 'A hoofed animal often kept for milk.'],
  ['GOLD', 'A yellow precious metal.'],
  ['GOLF', 'A game of hitting a ball into holes.'],
  ['GONE', 'No longer present; a form of “go.”'],
  ['GOOD', 'Of a pleasing or useful quality.'],
  ['HAIL', 'Frozen rain, or a greeting.'],
  ['HALL', 'A large room or passage.'],
  ['HAND', 'The part of an arm used for holding.'],
  ['HARD', 'Solid, or difficult.'],
  ['HARE', 'A long-eared animal related to a rabbit.'],
  ['HARM', 'Damage or injury.'],
  ['HATE', 'Feel a strong dislike.'],
  ['HAVE', 'Possess or experience.'],
  ['HEAD', 'The upper part of a body, or a leader.'],
  ['HEAL', 'Become healthy again.'],
  ['HEAP', 'A pile of things.'],
  ['HEAR', 'Perceive sound.'],
  ['HEAT', 'Warmth, or to make something hot.'],
  ['HILL', 'A raised area of land.'],
  ['HINT', 'A small clue or suggestion.'],
  ['HIRE', 'Employ someone or pay to use something.'],
  ['HIVE', 'A home for a colony of bees.'],
  ['HOLD', 'Keep in the hands or in place.'],
  ['HOLE', 'An opening or hollow space.'],
  ['HOME', 'The place where someone lives.'],
  ['HOOD', 'A covering for the head.'],
  ['HOOK', 'A curved piece used to catch or hang things.'],
  ['HOPE', 'A wish that something will happen.'],
  ['HORN', 'A hard head growth or a signalling instrument.'],
  ['HUNT', 'Search carefully for something.'],
  ['LAME', 'Unable to walk normally because of injury.'],
  ['LAMP', 'A device that gives light.'],
  ['LAND', 'Ground rather than water; also to arrive.'],
  ['LANE', 'A narrow road or marked strip.'],
  ['LARD', 'Fat from a pig, used in cooking.'],
  ['LAST', 'Final in order, or to continue.'],
  ['LATE', 'After the expected time.'],
  ['LEAD', 'Guide others; also a heavy metal.'],
  ['LEAF', 'A flat part of a plant that gathers light.'],
  ['LEAK', 'An unintended opening that lets fluid escape.'],
  ['LEAN', 'Tilt, or having little fat.'],
  ['LEAP', 'Jump a distance.'],
  ['LEND', 'Let someone use something temporarily.'],
  ['LENT', 'The past of “lend.”'],
  ['LEST', 'In order to avoid the risk that something happens.'],
  ['LIFE', 'The state of being alive.'],
  ['LIFT', 'Raise something.'],
  ['LIKE', 'Find pleasing, or similar to.'],
  ['LIME', 'A sour green citrus fruit.'],
  ['LINE', 'A long narrow mark or a row.'],
  ['LINK', 'A connection.'],
  ['LINT', 'Loose fibres from cloth.'],
  ['LIST', 'Items written one after another.'],
  ['LIVE', 'Be alive, or happening in real time.'],
  ['LOAD', 'Something carried.'],
  ['LOAF', 'Bread baked in one piece.'],
  ['LOAN', 'Something lent, often money.'],
  ['LONE', 'Without others.'],
  ['LONG', 'Extending a great distance or time.'],
  ['LOOK', 'Direct the eyes towards something.'],
  ['LORD', 'A title of rank or authority.'],
  ['LOSE', 'No longer have, or not win.'],
  ['LOST', 'Unable to find the way; the past of “lose.”'],
  ['LOVE', 'Deep affection.'],
  ['MADE', 'Created; the past of “make.”'],
  ['MAIL', 'Letters or parcels sent to someone.'],
  ['MAIN', 'Most important.'],
  ['MAKE', 'Create or produce.'],
  ['MALE', 'Of the sex that typically produces sperm.'],
  ['MANE', 'Long hair on an animal’s head or neck.'],
  ['MARE', 'An adult female horse.'],
  ['MASH', 'Crush into a soft mixture.'],
  ['MAST', 'An upright pole on a boat.'],
  ['MATE', 'A companion or one of a matching pair.'],
  ['MATH', 'The study of numbers and patterns.'],
  ['MEAL', 'Food eaten at one time.'],
  ['MEAN', 'Signify something, or an average.'],
  ['MEAT', 'Animal flesh used as food.'],
  ['MEET', 'Come together with someone.'],
  ['MEND', 'Repair something.'],
  ['MILE', 'A unit of distance.'],
  ['MILL', 'A building or machine for grinding.'],
  ['MIND', 'The part of a person that thinks and feels.'],
  ['MINE', 'Belonging to me, or a place where minerals are dug.'],
  ['MINT', 'An aromatic herb, or a place that makes coins.'],
  ['MIST', 'Tiny water droplets hanging in the air.'],
  ['MOAN', 'A low sound of discomfort.'],
  ['MODE', 'A way of operating.'],
  ['MOLD', 'A shaping container, or a type of fungus.'],
  ['MOLE', 'A small burrowing mammal.'],
  ['MOON', 'A natural satellite of a planet.'],
  ['MORE', 'A greater amount.'],
  ['MOST', 'The greatest amount.'],
  ['MOVE', 'Change position.'],
  ['MULE', 'The offspring of a donkey and a horse.'],
  ['MUSE', 'A source of inspiration; also to think deeply.'],
  ['MUST', 'Be required to.'],
  ['MUTE', 'Not producing sound; also to silence.'],
  ['NEAR', 'Not far away.'],
  ['NEAT', 'Tidy or carefully arranged.'],
  ['NEED', 'Something necessary.'],
  ['NEST', 'A structure made by an animal to hold its young.'],
  ['NINE', 'The number after eight.'],
  ['NONE', 'Not any.'],
  ['NOON', 'Twelve o’clock in the daytime.'],
  ['NOSE', 'The part of the face used for smelling.'],
  ['NOTE', 'A short written message or a musical sound.'],
  ['PACE', 'A speed of movement or a single step.'],
  ['PACK', 'Put things into a container, or a group.'],
  ['PAGE', 'One side of a sheet in a book.'],
  ['PAID', 'The past of “pay.”'],
  ['PAIL', 'A bucket.'],
  ['PAIN', 'An unpleasant physical or emotional sensation.'],
  ['PAIR', 'Two things considered together.'],
  ['PALE', 'Light in colour.'],
  ['PANE', 'A single sheet of window glass.'],
  ['PANT', 'Breathe quickly.'],
  ['PARE', 'Trim away an outer layer.'],
  ['PARK', 'A public green space, or to stop a vehicle.'],
  ['PART', 'A piece of a whole.'],
  ['PASS', 'Go past, or hand something over.'],
  ['PAST', 'The time before now.'],
  ['PATH', 'A way to walk or a course to follow.'],
  ['PAVE', 'Cover ground with a hard surface.'],
  ['PEAK', 'A highest point.'],
  ['PEAR', 'A fruit with a narrow top and rounded base.'],
  ['PEAT', 'Partly decayed plant material in wet ground.'],
  ['PEEL', 'An outer skin, or to remove it.'],
  ['PEER', 'Look closely, or someone of equal standing.'],
  ['PILL', 'A small solid dose of medicine.'],
  ['PINE', 'An evergreen tree, or to long for something.'],
  ['PINK', 'A light red colour.'],
  ['PINT', 'A unit of liquid volume.'],
  ['PLAN', 'An intended course of action.'],
  ['PLAY', 'Take part in a game or perform a role.'],
  ['POLE', 'A long slender rod.'],
  ['POLL', 'A vote or a survey.'],
  ['POND', 'A small body of still water.'],
  ['POOL', 'A body of water or shared resources.'],
  ['POOR', 'Having little money or being of low quality.'],
  ['PORE', 'A tiny opening in a surface.'],
  ['PORK', 'Meat from a pig.'],
  ['PORT', 'A harbour or a connection point.'],
  ['POST', 'An upright support, or to send a message.'],
  ['PULL', 'Draw something towards you.'],
  ['PUNT', 'Kick a ball before it touches the ground.'],
  ['PURE', 'Not mixed with other substances.'],
  ['READ', 'Understand written words.'],
  ['REAL', 'Actually existing.'],
  ['REED', 'A tall plant that grows in wet ground.'],
  ['REST', 'Pause to recover, or what remains.'],
  ['RIDE', 'Travel on an animal or in a vehicle.'],
  ['RING', 'A circular band, or a ringing sound.'],
  ['RISE', 'Move upwards.'],
  ['ROAD', 'A prepared way for travel.'],
  ['ROAM', 'Travel without a fixed route.'],
  ['ROLE', 'A part played or a function performed.'],
  ['ROLL', 'Move by turning over and over.'],
  ['ROOM', 'A space inside a building.'],
  ['ROOT', 'The part of a plant that takes in water.'],
  ['ROPE', 'Thick cord made of twisted fibres.'],
  ['ROSE', 'A flowering plant; also the past of “rise.”'],
  ['RULE', 'An instruction governing what is allowed.'],
  ['RUNG', 'A ladder step; also a form of “ring.”'],
  ['RUSH', 'Move with great hurry.'],
  ['RUST', 'The reddish coating that develops on wet iron.'],
  ['SAFE', 'Protected from danger.'],
  ['SAGE', 'An aromatic herb, or a wise person.'],
  ['SAIL', 'Cloth that catches wind to move a boat.'],
  ['SALE', 'An exchange for money.'],
  ['SAME', 'Not different.'],
  ['SAND', 'Small loose grains of rock.'],
  ['SANE', 'Able to think and judge reasonably.'],
  ['SANG', 'The past of “sing.”'],
  ['SANK', 'The past of “sink.”'],
  ['SAVE', 'Keep safe or put aside for later.'],
  ['SEAL', 'A marine mammal, or to close tightly.'],
  ['SEAM', 'A line where two pieces are joined.'],
  ['SEAR', 'Brown a surface with intense heat.'],
  ['SEAT', 'A place to sit.'],
  ['SEED', 'A plant part from which a new plant can grow.'],
  ['SEEK', 'Try to find.'],
  ['SEEM', 'Appear to be.'],
  ['SEEN', 'A form of the verb “see.”'],
  ['SELL', 'Exchange something for money.'],
  ['SEND', 'Cause something to go to a destination.'],
  ['SENT', 'The past of “send.”'],
  ['SEWN', 'Joined with stitches; a form of “sew.”'],
  ['SIDE', 'An edge, surface, or position next to something.'],
  ['SINE', 'A ratio relating an angle to sides of a triangle.'],
  ['SING', 'Make musical sounds with the voice.'],
  ['SINK', 'Go below a surface, or a basin for washing.'],
  ['SIRE', 'A male parent, especially of an animal.'],
  ['SITE', 'A place where something is located.'],
  ['SLAM', 'Shut or hit with force.'],
  ['SLAP', 'Strike with an open hand.'],
  ['SLIM', 'Thin in shape or small in amount.'],
  ['SLIP', 'Slide accidentally or move quietly.'],
  ['SOAR', 'Fly high or rise quickly.'],
  ['SOIL', 'Earth in which plants grow.'],
  ['SOLD', 'The past of “sell.”'],
  ['SOLE', 'The underside of a foot, or the only one.'],
  ['SOME', 'An unspecified amount.'],
  ['SONG', 'Words set to music.'],
  ['SOON', 'Before much time has passed.'],
  ['SORE', 'Painful or tender.'],
  ['SORT', 'A kind of thing, or to arrange in groups.'],
  ['SOWN', 'Scattered as seed; a form of “sow.”'],
  ['STAR', 'A distant sun, or a celebrated performer.'],
  ['SUNG', 'A form of the verb “sing.”'],
  ['SUNK', 'A form of the verb “sink.”'],
  ['SURE', 'Certain.'],
  ['SURF', 'Waves breaking near a shore.'],
  ['SWAM', 'The past of “swim.”'],
  ['SWAN', 'A large water bird with a long neck.'],
  ['SWIM', 'Move through water using the body.'],
  ['TAIL', 'The rear extension of an animal’s body.'],
  ['TAKE', 'Get hold of or carry away.'],
  ['TALE', 'A story.'],
  ['TALK', 'Communicate using spoken words.'],
  ['TALL', 'Of great height.'],
  ['TAME', 'Not wild, or to make less wild.'],
  ['TANK', 'A large container for liquid.'],
  ['TAPE', 'A narrow strip of material.'],
  ['TEAM', 'People working or playing together.'],
  ['TEAL', 'A small duck, or a blue-green colour.'],
  ['TEAR', 'A drop from the eye, or to rip.'],
  ['TELL', 'Give information in words.'],
  ['TEND', 'Look after, or be inclined to do something.'],
  ['TENT', 'A portable cloth shelter.'],
  ['TEST', 'A check of knowledge or performance.'],
  ['TILE', 'A thin flat piece used to cover a surface.'],
  ['TILL', 'Until, or to prepare soil for planting.'],
  ['TIME', 'The measure of when events happen.'],
  ['TINE', 'A pointed part of a fork.'],
  ['TIRE', 'Become weary; also a wheel’s outer covering.'],
  ['TOAD', 'An amphibian with typically dry, bumpy skin.'],
  ['TOLD', 'The past of “tell.”'],
  ['TOLL', 'A payment for passage, or a bell’s sound.'],
  ['TONE', 'A sound quality, or a shade of colour.'],
  ['TOOK', 'The past of “take.”'],
  ['TOOL', 'An object used to carry out a task.'],
  ['TORE', 'The past of “tear.”'],
  ['TORN', 'Ripped; a form of “tear.”'],
  ['TOWN', 'A settlement larger than a village.'],
  ['TUNE', 'A melody, or to adjust an instrument.'],
  ['TURN', 'Change direction.'],
  ['TURF', 'Grass and the soil held by its roots.'],
  ['VASE', 'A container used to display flowers.'],
  ['VAST', 'Very large.'],
  ['VEST', 'A sleeveless garment.'],
  ['VINE', 'A plant with a climbing or trailing stem.'],
  ['VOTE', 'A formal choice in a decision.'],
  ['WADE', 'Walk through water.'],
  ['WAGE', 'Payment for work.'],
  ['WAIL', 'A long cry.'],
  ['WAIT', 'Stay until something happens.'],
  ['WAKE', 'Stop sleeping.'],
  ['WALK', 'Travel on foot.'],
  ['WALL', 'A vertical structure that divides or encloses.'],
  ['WAND', 'A thin rod used as a symbol or imagined magic tool.'],
  ['WANE', 'Become smaller or weaker.'],
  ['WANT', 'Wish for something.'],
  ['WARD', 'A hospital division, or to keep something away.'],
  ['WARE', 'An article of a particular kind, as in pottery.'],
  ['WARM', 'Comfortably hot.'],
  ['WARN', 'Tell someone about a possible danger.'],
  ['WASH', 'Clean with water.'],
  ['WAVE', 'Moving water, or a greeting with the hand.'],
  ['WEAR', 'Have clothing on, or gradually damage through use.'],
  ['WEED', 'A plant growing where it is not wanted.'],
  ['WEEK', 'A period of seven days.'],
  ['WELL', 'In good health, or a deep water shaft.'],
  ['WENT', 'The past of “go.”'],
  ['WEST', 'The direction of sunset.'],
  ['WIDE', 'Extending far from side to side.'],
  ['WIFE', 'A married woman in relation to her spouse.'],
  ['WILD', 'Not domesticated or controlled.'],
  ['WILL', 'Determination, or a statement about the future.'],
  ['WIND', 'Moving air, or to turn around something.'],
  ['WINE', 'A fermented fruit drink.'],
  ['WING', 'A body part used for flight.'],
  ['WINK', 'Briefly close one eye.'],
  ['WIRE', 'A thin strand of metal.'],
  ['WISE', 'Showing good judgement.'],
  ['WISH', 'A hope for something.'],
  ['WOLF', 'A wild animal related to a dog.'],
  ['WOOD', 'The hard material in a tree’s trunk and branches.'],
  ['WOOL', 'Soft hair from sheep and similar animals.'],
  ['WORD', 'A unit of language with a meaning.'],
  ['WORE', 'The past of “wear.”'],
  ['WORN', 'Damaged through use; a form of “wear.”'],
  ['YEAR', 'The time a planet takes to orbit its star.'],
  ['YELL', 'Shout loudly.'],
];

export const DICTIONARY: readonly DictionaryEntry[] = vocabulary
  .map(([word, meaning]) => ({ word, meaning }))
  .sort((a, b) => a.word.localeCompare(b.word, 'en'));

export const WORDS: readonly string[] = DICTIONARY.map((entry) => entry.word);

export interface Puzzle {
  readonly id: string;
  readonly title: string;
  readonly start: string;
  readonly goal: string;
  readonly description: string;
}

export const PUZZLES: readonly Puzzle[] = [
  { id: 'cold-front', title: 'Cold front', start: 'COLD', goal: 'WARM', description: 'Bring a little warmth to four chilly letters.' },
  { id: 'change-of-heart', title: 'Change of heart', start: 'LOVE', goal: 'HATE', description: 'Turn the feeling around, one letter at a time.' },
  { id: 'inspiration', title: 'A little inspiration', start: 'MIND', goal: 'MUSE', description: 'Take a thought somewhere unexpected.' },
  { id: 'creature-feature', title: 'Creature feature', start: 'HEAD', goal: 'TAIL', description: 'An end-to-end transformation, without a leap.' },
  { id: 'shore-connection', title: 'Shore connection', start: 'SAND', goal: 'SURF', description: 'Find a way from the beach to the breakers.' },
  { id: 'into-the-air', title: 'Into the air', start: 'FISH', goal: 'BIRD', description: 'Trade a pair of fins for a pair of wings.' },
  { id: 'night-sky', title: 'Night sky', start: 'MOON', goal: 'STAR', description: 'Find another light in the same sky.' },
  { id: 'night-crossing', title: 'Night crossing', start: 'DUSK', goal: 'DAWN', description: 'Keep the connection going until morning.' },
];
