import { expect, test } from '@playwright/test';
import { SandGrid } from '../../src/projects/sand-script/engine';

test('falling conserves every pigment; walls, brushes, boundaries, and snapshots are exact', () => {
  const grid = new SandGrid(64, 64);
  grid.load('hourglass');
  const pigments = () => [2, 3, 4, 5, 6].map((pigment) => grid.cells.filter((cell) => cell === pigment).length);
  const counts = pigments();
  const before = grid.cells.slice();
  let moved = 0;
  for (let n = 0; n < 100; n++) moved += grid.step();
  expect(moved).toBeGreaterThan(0);
  expect(grid.cells).not.toEqual(before);
  expect(pigments()).toEqual(counts);
  expect(grid.countGrains()).toBe(counts.reduce((sum, value) => sum + value, 0));
  grid.empty();
  grid.brush(8, 12, 25, 12, 1, 'wall');
  grid.brush(8, 12, 25, 12, 1, 'sand', 4);
  expect(Array.from({ length: 18 }, (_, n) => grid.cells[n + 8 + 12 * grid.width])).toEqual(Array(18).fill(1));
  grid.brush(14, 4, 18, 4, 2, 'sand', 3);
  expect(grid.countGrains()).toBeGreaterThan(0);
  const edit = grid.snapshot();
  for (let n = 0; n < 20; n++) grid.step();
  grid.restore(edit);
  expect(grid.cells).toEqual(edit.cells);
  expect(grid.tick).toBe(edit.tick);
  grid.brush(-50, -50, 100, 0, 10, 'erase');
  expect(grid.cells.subarray(0, grid.width).every((cell) => cell === 1)).toBe(true);
  expect(Array.from({ length: grid.height }, (_, y) => grid.cells[y * grid.width]).every((cell) => cell === 1)).toBe(true);
});

test('edits have real undo, grain counts, pause, structures, and a local print', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('./projects/sand-script/');
  await expect(page.locator('#main-content > [data-stage]')).toHaveAttribute('data-ready', 'true');
  const tray = page.locator('[data-tray]');
  const canvas = tray.locator('canvas');
  await page.getByRole('button', { name: 'Pause animation', exact: true }).click();
  await page.waitForTimeout(100);
  const grains = await tray.getAttribute('data-grains');
  expect(Number(grains)).toBeGreaterThan(1000);
  const frozen = await canvas.evaluate((node: HTMLCanvasElement) => node.toDataURL());
  await page.waitForTimeout(140);
  expect(await canvas.evaluate((node: HTMLCanvasElement) => node.toDataURL())).toBe(frozen);
  await page.getByRole('button', { name: 'Clear grains', exact: true }).click();
  await expect(tray).toHaveAttribute('data-grains', '0');
  await page.getByRole('button', { name: 'Undo edit', exact: true }).click();
  await expect(tray).toHaveAttribute('data-grains', grains!);
  await expect(page.getByRole('button', { name: 'Play animation', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Empty tray', exact: true }).click();
  await canvas.focus();
  await page.keyboard.down('Space');
  await page.keyboard.press('ArrowRight');
  await page.keyboard.press('ArrowRight');
  await page.keyboard.up('Space');
  await expect.poll(async () => Number(await tray.getAttribute('data-grains'))).toBeGreaterThan(0);
  await page.keyboard.press('ControlOrMeta+z');
  await expect(tray).toHaveAttribute('data-grains', '0');
  await page.getByLabel('Start with a structure').selectOption('hourglass');
  await expect.poll(async () => Number(await tray.getAttribute('data-grains'))).toBeGreaterThan(500);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Save a sand print', exact: true }).click();
  expect((await download).suggestedFilename()).toBe('sand-script.png');
  expect(errors).toEqual([]);
});

test('the mobile reduced-motion tray supports material editing entirely by keyboard', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto('./projects/sand-script/');
  await expect(page.locator('.project-sand-script')).toHaveAttribute('data-motion', 'paused');
  const tray = page.locator('[data-tray]');
  const bounds = (await tray.boundingBox())!;
  expect(bounds.y).toBeLessThan(250);
  expect(bounds.height).toBeGreaterThan(330);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Empty tray', exact: true }).click();
  await tray.locator('canvas').focus();
  await page.keyboard.press('w');
  await page.keyboard.press('Enter');
  await expect(page.getByRole('button', { name: 'Build wall (W)', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.keyboard.press('b');
  await page.keyboard.press('Enter');
  await expect(tray).toHaveAttribute('data-grains', '0');
  await page.keyboard.press('e');
  await page.keyboard.press('Enter');
  await page.keyboard.press('b');
  await page.keyboard.press('Enter');
  await expect.poll(async () => Number(await tray.getAttribute('data-grains'))).toBeGreaterThan(0);
  await page.keyboard.press('p');
  await expect(page.getByRole('button', { name: 'Pause animation', exact: true })).toBeVisible();
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await expect(page.getByRole('button', { name: 'Play animation', exact: true })).toBeVisible();
});
